### ISSUE TITLE
first line removed

### ISSUE THREAD

**Issue by Detzler** [mrnocreativity/postcss-critical-split#6] opened 2017-07-26 20:38 UTC
Hi,

I got a case where the first line in a css block is removed each time the split operation runs.

original css:

```
/* critical:start */
.logobar {
  width: 80px;
  height: 100%;
  z-index: 999;
  position: fixed; }

/* critical:end */
```

css after split, "width" is missing:

```
.logobar {
    height: 100%;
    z-index: 999;
    position: fixed;
}
```

my grunt config is:

```
'split-rest': {
    src: ['css/style-sass.css'],
    dest: 'css/style-rest.css',
    options: {
        processors: [
            criticalSplit({
                output: 'rest'
            })
        ]
    }
},
```

Does anybody have an idea why the first line got removed?

**Comment by mrnocreativity** [comment] 2018-08-25 10:25
Hey @Detzler, i just added a new test to the repo.
Run it with `npm test weird-first-line-bug`.

It looks like the plugin is working as expected to me. Could you let me know if you managed to fix this?

**Comment by mrnocreativity** [comment] 2019-04-29 12:46
I'm closing this issue as it's not been able to be reproduced and there was no new feedback.

**Closed by mrnocreativity** 2019-04-29 12:46 UTC
Labels: unable to reproduce, waiting for feedback
